/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
    _type: "sanity.imagePaletteSwatch";
    background?: string;
    foreground?: string;
    population?: number;
    title?: string;
};

export type SanityImagePalette = {
    _type: "sanity.imagePalette";
    darkMuted?: SanityImagePaletteSwatch;
    lightVibrant?: SanityImagePaletteSwatch;
    darkVibrant?: SanityImagePaletteSwatch;
    vibrant?: SanityImagePaletteSwatch;
    dominant?: SanityImagePaletteSwatch;
    lightMuted?: SanityImagePaletteSwatch;
    muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
    _type: "sanity.imageDimensions";
    height?: number;
    width?: number;
    aspectRatio?: number;
};

export type SanityFileAsset = {
    _id: string;
    _type: "sanity.fileAsset";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash?: string;
    extension?: string;
    mimeType?: string;
    size?: number;
    assetId?: string;
    uploadId?: string;
    path?: string;
    url?: string;
    source?: SanityAssetSourceData;
};

export type Geopoint = {
    _type: "geopoint";
    lat?: number;
    lng?: number;
    alt?: number;
};

export type BlogPost = {
    _id: string;
    _type: "blogPost";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string;
    synopsis: string;
    slug: Slug;
    image?: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    };
    body?: string;
};

export type ProjectPost = {
    _id: string;
    _type: "projectPost";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string;
    synopsis: string;
    slug: Slug;
    project: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "project";
    };
    image?: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    };
    body?: string;
};

export type Project = {
    _id: string;
    _type: "project";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string;
    slug: Slug;
    synopsis: string;
    intro?: string;
    image?: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    };
    siteUrl?: string;
    githubUrl?: string;
};

export type SanityImageCrop = {
    _type: "sanity.imageCrop";
    top?: number;
    bottom?: number;
    left?: number;
    right?: number;
};

export type SanityImageHotspot = {
    _type: "sanity.imageHotspot";
    x?: number;
    y?: number;
    height?: number;
    width?: number;
};

export type SanityImageAsset = {
    _id: string;
    _type: "sanity.imageAsset";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash?: string;
    extension?: string;
    mimeType?: string;
    size?: number;
    assetId?: string;
    uploadId?: string;
    path?: string;
    url?: string;
    metadata?: SanityImageMetadata;
    source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
    _type: "sanity.assetSourceData";
    name?: string;
    id?: string;
    url?: string;
};

export type SanityImageMetadata = {
    _type: "sanity.imageMetadata";
    location?: Geopoint;
    dimensions?: SanityImageDimensions;
    palette?: SanityImagePalette;
    lqip?: string;
    blurHash?: string;
    hasAlpha?: boolean;
    isOpaque?: boolean;
};

export type Slug = {
    _type: "slug";
    current: string;
    source?: string;
};

export type Markdown = string;

export type AllSanitySchemaTypes =
    | SanityImagePaletteSwatch
    | SanityImagePalette
    | SanityImageDimensions
    | SanityFileAsset
    | Geopoint
    | BlogPost
    | ProjectPost
    | Project
    | SanityImageCrop
    | SanityImageHotspot
    | SanityImageAsset
    | SanityAssetSourceData
    | SanityImageMetadata
    | Slug
    | Markdown;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./app/sanity/queries/blog.ts
// Variable: GET_BLOG_POSTS_QUERY
// Query: *[_type == 'blogPost'] | order(_createdAt desc) {title, synopsis, 'slug': slug.current, image}
export type GET_BLOG_POSTS_QUERYResult = Array<{
    title: string;
    synopsis: string;
    slug: string;
    image: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    } | null;
}>;
// Variable: GET_BLOG_POST_QUERY
// Query: *[_type == 'blogPost' && slug.current == $blogPostSlug][0] | {title, synopsis, body, image}
export type GET_BLOG_POST_QUERYResult = {
    title: string;
    synopsis: string;
    body: string | null;
    image: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    } | null;
} | null;

// Source: ./app/sanity/queries/project.ts
// Variable: GET_PROJECTS_QUERY
// Query: *[_type == 'project'] | order(_createdAt desc) {'slug': slug.current, title, synopsis, image}
export type GET_PROJECTS_QUERYResult = Array<{
    slug: string;
    title: string;
    synopsis: string;
    image: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    } | null;
}>;
// Variable: GET_PROJECT_QUERY
// Query: *[_type == 'project' && slug.current == $projectSlug][0] | {title, synopsis, description, image, siteUrl, githubUrl }
export type GET_PROJECT_QUERYResult = {
    title: string;
    synopsis: string;
    description: null;
    image: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    } | null;
    siteUrl: string | null;
    githubUrl: string | null;
} | null;
// Variable: GET_PROJECT_POSTS_QUERY
// Query: *[_type == 'projectPost' && $projectSlug == project->slug.current] | order(_createdAt desc) {title, synopsis, 'slug': slug.current, image}
export type GET_PROJECT_POSTS_QUERYResult = Array<{
    title: string;
    synopsis: string;
    slug: string;
    image: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    } | null;
}>;
// Variable: GET_PROJECT_POST_QUERY
// Query: *[_type == 'projectPost' && $projectSlug == project->slug.current && $projectPostSlug == slug.current][0] | {title, synopsis, body, image}
export type GET_PROJECT_POST_QUERYResult = {
    title: string;
    synopsis: string;
    body: string | null;
    image: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
    interface SanityQueries {
        "*[_type == 'blogPost'] | order(_createdAt desc) {title, synopsis, 'slug': slug.current, image}": GET_BLOG_POSTS_QUERYResult;
        "*[_type == 'blogPost' && slug.current == $blogPostSlug][0] | {title, synopsis, body, image}": GET_BLOG_POST_QUERYResult;
        "*[_type == 'project'] | order(_createdAt desc) {'slug': slug.current, title, synopsis, image}": GET_PROJECTS_QUERYResult;
        "*[_type == 'project' && slug.current == $projectSlug][0] | {title, synopsis, description, image, siteUrl, githubUrl }": GET_PROJECT_QUERYResult;
        "*[_type == 'projectPost' && $projectSlug == project->slug.current] | order(_createdAt desc) {title, synopsis, 'slug': slug.current, image}": GET_PROJECT_POSTS_QUERYResult;
        "*[_type == 'projectPost' && $projectSlug == project->slug.current && $projectPostSlug == slug.current][0] | {title, synopsis, body, image}": GET_PROJECT_POST_QUERYResult;
    }
}
