overwrite: true
schema: "./schema.graphql"
generates:
    ./app/graphql/:
        plugins:
            - "typescript"
            - "typescript-resolvers"
        preset: "client"
        config:
            useIndexSignature: true
            contextType: "../index#MyContext"
